[package]
name = "timetrackd"
version = "0.1.0"
authors = ["Joel Schumacher <joelschum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
